export interface CountryIso3166 {
    code: string;
    alpha3Code: string;
    alpha2Code: string;
    name: string;
}

export const countriesIso3166: CountryIso3166[] = [
    { "code": "004", "alpha3Code": "AFG", "alpha2Code": "AF", "name": "Afganistán" },
    { "code": "248", "alpha3Code": "ALA", "alpha2Code": "AX", "name": "Åland" },
    { "code": "008", "alpha3Code": "ALB", "alpha2Code": "AL", "name": "Albania" },
    { "code": "276", "alpha3Code": "DEU", "alpha2Code": "DE", "name": "Alemania" },
    { "code": "020", "alpha3Code": "AND", "alpha2Code": "AD", "name": "Andorra" },
    { "code": "024", "alpha3Code": "AGO", "alpha2Code": "AO", "name": "Angola" },
    { "code": "660", "alpha3Code": "AIA", "alpha2Code": "AI", "name": "Anguila" },
    { "code": "010", "alpha3Code": "ATA", "alpha2Code": "AQ", "name": "Antártida" },
    { "code": "028", "alpha3Code": "ATG", "alpha2Code": "AG", "name": "Antigua y Barbuda" },
    { "code": "530", "alpha3Code": "ANT", "alpha2Code": "AN", "name": "Antillas Neerlandesas" },
    { "code": "682", "alpha3Code": "SAU", "alpha2Code": "SA", "name": "Arabia Saudita" },
    { "code": "012", "alpha3Code": "DZA", "alpha2Code": "DZ", "name": "Argelia" },
    { "code": "032", "alpha3Code": "ARG", "alpha2Code": "AR", "name": "Argentina" },
    { "code": "051", "alpha3Code": "ARM", "alpha2Code": "AM", "name": "Armenia" },
    { "code": "533", "alpha3Code": "ABW", "alpha2Code": "AW", "name": "Aruba" },
    { "code": "036", "alpha3Code": "AUS", "alpha2Code": "AU", "name": "Australia" },
    { "code": "040", "alpha3Code": "AUT", "alpha2Code": "AT", "name": "Austria" },
    { "code": "031", "alpha3Code": "AZE", "alpha2Code": "AZ", "name": "Azerbaiyán" },
    { "code": "044", "alpha3Code": "BHS", "alpha2Code": "BS", "name": "Bahamas" },
    { "code": "048", "alpha3Code": "BHR", "alpha2Code": "BH", "name": "Bahréin" },
    { "code": "050", "alpha3Code": "BGD", "alpha2Code": "BD", "name": "Bangladesh" },
    { "code": "052", "alpha3Code": "BRB", "alpha2Code": "BB", "name": "Barbados" },
    { "code": "112", "alpha3Code": "BLR", "alpha2Code": "BY", "name": "Bielorrusia" },
    { "code": "056", "alpha3Code": "BEL", "alpha2Code": "BE", "name": "Bélgica" },
    { "code": "084", "alpha3Code": "BLZ", "alpha2Code": "BZ", "name": "Belice" },
    { "code": "204", "alpha3Code": "BEN", "alpha2Code": "BJ", "name": "Benín" },
    { "code": "060", "alpha3Code": "BMU", "alpha2Code": "BM", "name": "Bermudas" },
    { "code": "064", "alpha3Code": "BTN", "alpha2Code": "BT", "name": "Bután" },
    { "code": "068", "alpha3Code": "BOL", "alpha2Code": "BO", "name": "Bolivia" },
    { "code": "070", "alpha3Code": "BIH", "alpha2Code": "BA", "name": "Bosnia y Herzegovina" },
    { "code": "072", "alpha3Code": "BWA", "alpha2Code": "BW", "name": "Botsuana" },
    { "code": "074", "alpha3Code": "BVT", "alpha2Code": "BV", "name": "Isla Bouvet" },
    { "code": "076", "alpha3Code": "BRA", "alpha2Code": "BR", "name": "Brasil" },
    { "code": "096", "alpha3Code": "BRN", "alpha2Code": "BN", "name": "Brunéi" },
    { "code": "100", "alpha3Code": "BGR", "alpha2Code": "BG", "name": "Bulgaria" },
    { "code": "854", "alpha3Code": "BFA", "alpha2Code": "BF", "name": "Burkina Faso" },
    { "code": "108", "alpha3Code": "BDI", "alpha2Code": "BI", "name": "Burundi" },
    { "code": "132", "alpha3Code": "CPV", "alpha2Code": "CV", "name": "Cabo Verde" },
    { "code": "136", "alpha3Code": "CYM", "alpha2Code": "KY", "name": "Islas Caimán" },
    { "code": "116", "alpha3Code": "KHM", "alpha2Code": "KH", "name": "Camboya" },
    { "code": "120", "alpha3Code": "CMR", "alpha2Code": "CM", "name": "Camerún" },
    { "code": "124", "alpha3Code": "CAN", "alpha2Code": "CA", "name": "Canadá" },
    { "code": "140", "alpha3Code": "CAF", "alpha2Code": "CF", "name": "República Centroafricana" },
    { "code": "148", "alpha3Code": "TCD", "alpha2Code": "TD", "name": "Chad" },
    { "code": "203", "alpha3Code": "CZE", "alpha2Code": "CZ", "name": "República Checa" },
    { "code": "152", "alpha3Code": "CHL", "alpha2Code": "CL", "name": "Chile" },
    { "code": "156", "alpha3Code": "CHN", "alpha2Code": "CN", "name": "China" },
    { "code": "196", "alpha3Code": "CYP", "alpha2Code": "CY", "name": "Chipre" },
    { "code": "166", "alpha3Code": "CCK", "alpha2Code": "CC", "name": "Islas Cocos" },
    { "code": "170", "alpha3Code": "COL", "alpha2Code": "CO", "name": "Colombia" },
    { "code": "178", "alpha3Code": "COG", "alpha2Code": "CG", "name": "República del Congo" },
    { "code": "180", "alpha3Code": "COD", "alpha2Code": "CD", "name": "República Democrática del Congo" },
    { "code": "188", "alpha3Code": "CRI", "alpha2Code": "CR", "name": "Costa Rica" },
    { "code": "191", "alpha3Code": "HRV", "alpha2Code": "HR", "name": "Croacia" },
    { "code": "192", "alpha3Code": "CUB", "alpha2Code": "CU", "name": "Cuba" },
    { "code": "208", "alpha3Code": "DNK", "alpha2Code": "DK", "name": "Dinamarca" },
    { "code": "214", "alpha3Code": "DOM", "alpha2Code": "DO", "name": "República Dominicana" },
    { "code": "218", "alpha3Code": "ECU", "alpha2Code": "EC", "name": "Ecuador" },
    { "code": "818", "alpha3Code": "EGY", "alpha2Code": "EG", "name": "Egipto" },
    { "code": "222", "alpha3Code": "SLV", "alpha2Code": "SV", "name": "El Salvador" },
    { "code": "784", "alpha3Code": "ARE", "alpha2Code": "AE", "name": "Emiratos Árabes Unidos" },
    { "code": "724", "alpha3Code": "ESP", "alpha2Code": "ES", "name": "España" },
    { "code": "840", "alpha3Code": "USA", "alpha2Code": "US", "name": "Estados Unidos" },
    { "code": "250", "alpha3Code": "FRA", "alpha2Code": "FR", "name": "Francia" },
    { "code": "356", "alpha3Code": "IND", "alpha2Code": "IN", "name": "India" },
    { "code": "380", "alpha3Code": "ITA", "alpha2Code": "IT", "name": "Italia" },
    { "code": "392", "alpha3Code": "JPN", "alpha2Code": "JP", "name": "Japón" },
    { "code": "484", "alpha3Code": "MEX", "alpha2Code": "MX", "name": "México" },
    { "code": "528", "alpha3Code": "NLD", "alpha2Code": "NL", "name": "Países Bajos" },
    { "code": "604", "alpha3Code": "PER", "alpha2Code": "PE", "name": "Perú" },
    { "code": "616", "alpha3Code": "POL", "alpha2Code": "PL", "name": "Polonia" },
    { "code": "620", "alpha3Code": "PRT", "alpha2Code": "PT", "name": "Portugal" },
    { "code": "826", "alpha3Code": "GBR", "alpha2Code": "GB", "name": "Reino Unido" },
    { "code": "643", "alpha3Code": "RUS", "alpha2Code": "RU", "name": "Rusia" },
    { "code": "710", "alpha3Code": "ZAF", "alpha2Code": "ZA", "name": "Sudáfrica" },
    { "code": "752", "alpha3Code": "SWE", "alpha2Code": "SE", "name": "Suecia" },
    { "code": "756", "alpha3Code": "CHE", "alpha2Code": "CH", "name": "Suiza" },
    { "code": "858", "alpha3Code": "URY", "alpha2Code": "UY", "name": "Uruguay" },
    { "code": "862", "alpha3Code": "VEN", "alpha2Code": "VE", "name": "Venezuela" },
    { "code": "894", "alpha3Code": "ZMB", "alpha2Code": "ZM", "name": "Zambia" },
    { "code": "716", "alpha3Code": "ZWE", "alpha2Code": "ZW", "name": "Zimbabue" }
];