export enum IdType {
    REGISTRO_CIVIL = 'RC',
    TARJETA_IDENTIDAD = 'TI',
    CEDULA_CIUDADANIA = 'CC',
    CEDULA_EXTRANJERIA = 'CE',
    PASAPORTE = 'PA',
    TARJETA_EXTRANJERIA = 'TE',
    DOCUMENTO_IDENTIFICACION_EXTRANJERO = 'DIE',
    PERMISO_ESPECIAL_PERMANENCIA = 'PEP'
}